---
trust-domain: mobile
treeherder:
    group-names:
        'bump': 'Bump dependencies'
        'debug': 'Builds made for testing'
        'Fetch': 'Fetch and store content'
        'I': 'Docker Image Builds'
        'Rap': 'Raptor tests'
        'Rap-P': 'Raptor power tests'
        'TL': 'Toolchain builds for Linux 64-bits'

task-priority: lowest

taskgraph:
    register: rb_taskgraph:register
    repositories:
        mobile:
            name: "reference-browser"
    cached-task-prefix: mobile.v2.reference-browser

workers:
    aliases:
        b-android:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux-gcp'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: mobile-t-signing
        images:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'images-gcp'
        misc:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux-gcp'
        push-apk:
            provisioner: scriptworker-k8s
            implementation: scriptworker-pushapk
            os: scriptworker
            worker-type: 'mobile-{level}-pushapk'
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": mobile-3-signing
                    default: mobile-t-signing
        t-bitbar.*:
            provisioner: proj-autophone
            implementation: generic-worker
            os: linux-bitbar
            worker-type: 'gecko-{alias}'

scriptworker:
    scope-prefix: project:mobile:reference-browser:releng
